VkService/Controllers/VkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper.QueryableExtensions;
using CostEffectiveCode.Common;
using CostEffectiveCode.Cqrs;
using CostEffectiveCode.Ddd;
using CostEffectiveCode.Ddd.Entities;
using VkService.App.Service;
using VkService.DAL.Entities;

namespace VkService.Controllers
{
    public class VkController : Controller
    {
        private readonly IQuery<IEnumerable<UserDto>> _allUsers;
        private readonly IQuery<int, UserDto> _byId;
        private readonly IQuery<int, IEnumerable<UserDto>> _friendsUser;
        private readonly ILoaderFriends _vkService;

        public VkController(IQuery<IEnumerable<UserDto>> allUsers,
            IQuery<int, UserDto> byId,
            IQuery<int, IEnumerable<UserDto>> friendsUser,
            ILoaderFriends vkService)
        {
            _allUsers = allUsers;
            _byId = byId;
            _friendsUser = friendsUser;
            _vkService = vkService;
        }

        // GET: Vk
        public ActionResult Index()
        {
            var users = _allUsers.Ask();
            return View(users);
        }
        public ActionResult Users(int id)
        {
            var user = _byId.Ask(id);
            ViewBag.Login = user.Login;
            ViewBag.Data = user.DataRunWd;
            ViewBag.Name = user.Name;
            return View(_friendsUser.Ask(id));
        }

        public ActionResult StartService()
        {
            _vkService.Start(Config.Browser,Config.WaitTimeout,Config.Login,Config.Password,Config.Iteration);
            return Index();
        }

        public bool IsRun()
        {
            return LoaderFriends.FlagRun;
        }
    }

    public class UsersQuery :
        IQuery<IEnumerable<UserDto>>,
        IQuery<int, UserDto>,
        IQuery<int, IEnumerable<UserDto>>
    {
        private readonly ILinqProvider _linqProvider;
        private readonly IUnitOfWork _uof;
        private readonly IMapper _mapper;

        public UsersQuery(ILinqProvider linqProvider, IUnitOfWork uof, IMapper mapper)
        {
            _linqProvider = linqProvider;
            _uof = uof;
            _mapper = mapper;
        }

        public IEnumerable<UserDto> Ask()
        {
            return _linqProvider
                .Query<User>()
                .ProjectTo<UserDto>()
                .ToList();
        }

        public UserDto Ask(int id)
        {
            var user =  _uof.Find<User>(id);
            return _mapper.Map<UserDto>(user);
        }

        IEnumerable<UserDto> IQuery<int, IEnumerable<UserDto>>.Ask(int spec)
        {
            return _linqProvider.Query<User>()
                .Where(x => x.ParentId == spec)
                .ProjectTo<UserDto>()
                .ToList();
        }
    }

    public class UserDto : HasIdBase<int>
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Login { get; set; }
        public string Status { get; set; }
        public int Rate { get; set; }
        public string Url { get; set; }
        public DateTime DataRunWd { get; set; }
        public string Work { get; set; }
        public int MatualFriends { get; set; } = 0;
    }
}

VkService/Views/Shared/_Layout.cshtml
@using CostEffectiveCode.Extensions
@using VkService.Controllers

﻿<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @{
                    ViewBag.flag = ((VkController) this.ViewContext.Controller).IsRun();
                }
                @Html.ActionLink("VkService", "Index", "Vk", null, new {@class = "navbar-brand"})
                 @Html.ActionLink("Start", null, null, null, (@ViewBag.flag == false) ? (object)
                        new {@id = "vkStart", onclick="startVkService()",@class="btn btn-lg btn-primary", style="margin-top: 2px;"} :
                        new{disabled="disabled", @id = "vkStart", onclick="startVkService()",@class="btn btn-lg btn-primary", style="margin-top: 2px;" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
<script>
    function startVkService() {
                $('#vkStart').attr('disabled', 'disabled');
                window.alert('Cервис запущен');
        $.ajax({
            type: "POST",
            url: "@Url.Action("StartService", "Vk")"
        });
    }

</script>
</body>
</html>

VkService/Views/Vk/Index.cshtml
@model IEnumerable<VkService.Controllers.UserDto>

@{
    ViewBag.Title = "Главная страница";
}

    <h2>Таблица логинов:</h2>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Login)
            </th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.ActionLink(item.Login, "Users", new { id=item.Id })
                    <div class="row">
                    </div>
                </td>
            </tr>
        }
    </table>
<div class="row">
</div>

VkService/Views/Vk/Users.cshtml
@model IEnumerable<VkService.Controllers.UserDto>

@{
    ViewBag.Title = "Друзья";
}

<h4>Друзья пользователя @ViewBag.Login  последнее обновление данных для пользователя @ViewBag.Name было @ViewBag.Data
</h4>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Url)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataRunWd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Work)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Url)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataRunWd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Work)
        </td>
    </tr>
}

</table>